pphp.lo: /home/ben/Dev/pphp/ext/pphp.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ben/Dev/pphp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ben/Dev/pphp/ext/pphp.c -o pphp.lo 
$(phplibdir)/pphp.la: ./pphp.la
	$(LIBTOOL) --mode=install cp ./pphp.la $(phplibdir)

./pphp.la: $(shared_objects_pphp) $(PPHP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_pphp) $(PPHP_SHARED_LIBADD)

